Feature/day5
lokks307/training-newbie pull request #16
Opened 2023-08-15 11:55 UTC by redcatsh

2023-08-17 13:55 UTC, doscode-kr requested changes

2023-08-17 13:55 UTC, doscode-kr commented on javascript/song/ex000_002.js
> +}
오.. 리듀스 인덱스를 저장하는 신박한 방법..

저는 조금 더 쉽게 생각해봤어요.
1. 2의 위치(인덱스) 다 구하고  ==> 이런 역할을 하는 함수를 만듭니다.
2. (0, 1, 2 이상) 각각의 케이스에 대해 대응하는 코드 작성

어느게 더 쉬울까요? 

```js
function ex59BoundaryOf2(arr) {
    var answer = [];
    
    const idxList = getAllIndexes(arr, 2)
    const len = idxList.length
    
    
    switch (len){
        case 0 : return [-1];
        case 1 : return [2];
        case 2 : 
        default :
            var last = idxList[len-1]+1;
            var start = idxList[0]
            
            return arr.slice(start, last)
    }
}

function getAllIndexes(arr, val) {
    var indexes = [], i;
    for(i = 0; i < arr.length; i++)
        if (arr[i] === val)
            indexes.push(i);
    return indexes;
}
```

앞에서는 가능하면 map을 쓰라고 했지만, 이런 요구사항에서는 사용할 수 없어요.
가능하면 map을 사용한다 [o]
무조건 map을 사용한다 [x] 

reduce도 마찬가지..

2023-08-17 13:55 UTC, doscode-kr commented on javascript/song/ex000_002.js
> +  if (slicedArr.length === 0) return [-1];
sliceArr.length 말고 indices.length를 이용해서 필터링해도 동작했을 거예요

예외를 다루는 코드는 위에 있는게 더 좋아요.
처리하고 머리에서 지우면 되니까요.

2023-08-17 13:55 UTC, doscode-kr commented on javascript/song/ex000_002.js
> +
슬라이스를 두 번 호출하는 것보다
start, end index를 계산하는 코드가 더 좋아요.

```js
function ex60SliceArray(arr, query) {
  for (let i = 0; i < query.length; i++) {
    const start = i % 2 === 0 ? 0 : query[i];
    const end = i % 2 === 0 ? query[i] + 1 : undefined;

    arr = arr.slice(start, end);
  }
  return arr;
}
```

지금은 문제가 단순하지만, 현실의 문제는 조금 더 복잡해요.
특정 연산을 수행하는 코드가 중구난방으로 작성되어있으면 코드를 수정하기 힘들어져요.
정확히는  A지점을 수정하면 B지점에서 오류가 날거예요. 
그런데 만약, 복붙한 함수가 두개가 아니라 20개라면...? 👻

2023-08-17 13:55 UTC, doscode-kr commented on javascript/song/ex000_002.js
> +
한 줄에 표현하기 복잡하다고 느끼면, 나누면 더 좋아요.

```js
function ex62SwapOrder(num_list, n) {
  const part1 = num_list.slice(n);
  const part2 = num_list.slice(0, n);
  return part1.concat(part2);
}
```
이렇게 쓰고 나면, 다른게 보이죠.
'아. spread 연산자 써야겠다.' 라고

```js
function ex62SwapOrder(num_list, n) {
  const part1 = num_list.slice(n);
  const part2 = num_list.slice(0, n);
  return [...part1, ...part2];
}
```

재밌는 사실이 하나 있어요. 중간 과정을 거치지 않으면 spread operator를 사용해야겠다는 생각이 잘 들지 않습니다.

2023-08-17 13:55 UTC, doscode-kr commented on javascript/song/ex000_002.js
> +  } else if (str_list[idx] === "l") {
예외 상황을 먼저 처리하는 건 잘 하셨어요.
그런데 이 때, else if 대신 if를 쓰는게 더 좋습니다.
else로 엮으면 이전 조건을 머리속에서 외워야합니다.
그런데 이전 조건은 이미 return으로 종결된 사건이잖아요?

else가 필요하지 않아요. 로직이 조금이라도 복잡해지면, 사람이 잘못 해석하는 일이 생깁니다.

그리고 위에서 말한 것과 같은 상황이 바로 나왔네요...

slice를 두 곳에서 호출하지 말고, start와 end index를 각각 구하세요.


```js
function ex63LeftRight(str_list) {
  const idx = str_list.findIndex((el) => el === "l" || el === "r");
  
  if (idx === -1) {
    return [];
  }
  
  const isL = str_list[idx] === "l";
  const start = isL ? 0 : idx+1;
  const end = isL ? idx : undefined;
  
  return str_list.slice(start, end);
}
```

2023-08-17 13:55 UTC, doscode-kr commented on javascript/song/ex000_002.js
> +  } else if (str_list[idx] === "l") {
이 코드도 코드의 각 줄을 1:1로 해석하면서 이해해보세요.

제가 작성한 코드는 이렇게 읽을 수 있어요.
str list에서 'l' 또는 'r'의 위치를 찾는다.
없다면 빈 배열 반환.
// else로 묶을 필요가 없어짐. 이제 항상 l 또는 r이 있는 상황이니까요.

이게.. l인가?
l이라면 0부터 시작한다. 아니면 l의 위치+1이 시작 위치다
l이라면 l의 위치가 종료지점 end다. 아니라면 끝까지(undefined) 가져온다.

start부터 end까지 slice 실행

2023-08-17 13:55 UTC, doscode-kr commented on javascript/song/ex000_002.js
> +}
💯

2023-08-17 13:55 UTC, doscode-kr commented on javascript/song/ex000_002.js
> +      arr[i] += 1;
arr[i]++; 하셔도 괜찮았을 것 같아요.

2023-08-17 13:55 UTC, doscode-kr commented on javascript/song/ex000_002.js
> +
맵 내부가 너무 복잡해요. 이런 경우 함수를 하나만 더 만들면 생각이 더 단순해져요.

```js
function transformElement(el) {
  if (el >= 50 && el % 2 === 0) {
    return el / 2;
  } else if (el < 50 && el % 2 !== 0) {
    return el * 2;
  }
  return el;
}

function ex71ConvertSeq(arr) {
  return arr.map(transformElement);
}
```

2023-08-17 13:55 UTC, doscode-kr commented on javascript/song/ex000_002.js
> +
이것도 함수를 두개로 나누는게 더 이해하기 쉬울 거예요

```js
function transformElement(el) {
  if (el >= 50 && el % 2 === 0) {
    return el / 2;
  } else if (el < 50 && el % 2 !== 0) {
    return el * 2 + 1;
  }
  return el;
}

function ex72ConvertSeq(arr) {
  let count = 0;

  while (!arr.every((el) => transformElement(el) === el)) {
    arr = arr.map(transformElement);
    count++;
  }

  return count;
}

```

2023-08-17 13:55 UTC, doscode-kr commented on javascript/song/ex000_002.js
> +
```js
function applyOperations(num) {
  if (num % 2 === 0) {
    return num / 2;
  } else {
    return (num - 1) / 2;
  }
}

function ex73CountForOne(num_list) {
  let count = 0;

  for (let num of num_list) {
    while (num !== 1) {
      num = applyOperations(num);
      count++;
    }
  }

  return count;
}
```

2023-08-17 13:55 UTC, doscode-kr commented on javascript/song/ex000_002.js
> +  if (num_list.length >= 11) {
매직 넘버에 이름을 지어주면 더 좋아요.

const lengthThreshold = 11;

2023-08-18 09:04 UTC, redcatsh commented on javascript/song/ex000_002.js
> +
원래 말씀해주신 것처럼 풀었다가 더 간단하게 풀어보고 싶어서 고친 코드였는데..ㅎㅎ 한 줄에 복잡하게 쓰는 것보다 나누는 게 더 좋다는 말씀 새기겠습니다 :)

2023-08-21 00:32 UTC, doscode-kr commented
다른 PR에서 수정한 걸 보았습니다. 이 PR은 머지합니다.

2023-08-21 00:32 UTC, merged