[add] first quiz
lokks307/training-newbie pull request #3
Opened 2023-08-09 04:58 UTC by redcatsh

1번째 문제입니다.

2023-08-09 08:58 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +  });
위에 작성한 코드와 완전 동일한 코드가 있네요.
atomic한 코드를 복사 & 붙여넣기하는건 죄악과도 같습니다.

저라면 rl객체를 반환하는 함수를 하나 만들 것 같아요.

2023-08-09 08:58 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +  });
사고방식을 설명하면
(이전)
readline을 require로 가져오고,
readline에서 인터페이스 객체를 만들고, 이때 process의 stdin과 stdout을 각각 input과 output으로 받아야지.
(...)

(이후)
rlInterface 만들고 (어떻게 생겼는지 생각할 필요 없음)
(...)

2023-08-09 09:03 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +    input = line.split(" ");
그럼 코드를 더 단순하게 작성할 수 있을 것 같아요.

let input = [];
const rl = rlInterface(ex1);

이렇게

2023-08-09 09:04 UTC, doscode-kr requested changes

2023-08-09 09:04 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +  });
위에서 가르쳐준대로 바꿔보세요.

2023-08-09 09:04 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +    output: process.stdout,
여기도

2023-08-09 09:22 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +    n % 2 === 0 ? console.log(`${n} is even`) : console.log(`${n} is odd`);
~300 이하 마세이 금지~
1년 이하 3항 연산자 금지...............

3항 연산자는 잘못이 없어요.
다만, 세살 버릇 여든 간다라는 속담이 있죠.?
연산과 출력을 같이 하는 못된 습관이 복잡한 로직을 구현할 때 드러날 수 있어요.
그러면 그 곳에 악마가 소환됩니다.
누구도 손댈 수 없는 코드가 만들어져요.

2023-08-09 14:04 UTC, redcatsh commented on javascript/song/ex000_001.js
> +  });
그 동일한 코드 부분(입력받는 부분)이 프로그래머스 풀 때 자동으로 입력되어 있는 코드여서 건들지 않고 
저는 출력하는 코드만 추가해서 그런 것 같아요..!
그리고 저 입력받는 부분이 어떤 코드인지 사실 아직 잘 모르겠습니다 ..ㅠ

2023-08-09 17:06 UTC, redcatsh commented on javascript/song/ex000_001.js
> +    input = line.split(" ");
readline 모듈에 대해 찾아보고 있는데..
line.split(" ") 하는 코드가 입력 받은 값을 처리하는 부분인데 이 부분을 output으로 옮긴다는 말이 이해가 잘 안되는 것 같습니다ㅜ

2023-08-10 01:29 UTC, doscode-kr requested changes

2023-08-10 01:29 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +  });
곧 예제 코드를 만들어 드릴게요.

2023-08-10 01:29 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +  });
1번 문제 푸실 때 아래 코드를 넣어보세요. 동작할 거예요.

```javascript
let input;

solveThis(ex2);

function ex1() {
    // 3. 프로그래머스를 위한 문제 풀이 구조의 틀을 고정해놨습니다. 
    // 이제 다른 구조를 신경쓰지 마시고, 처리할 입력이 `input`에 있다고
    // 가정하고 핵심 코드만 작성하면 됩니다.
    console.log(input);
}

function ex2() {
    ex2Output(input.split(" "))
}

function ex2Output([a, b]){
    console.log(`a = ${a}`);
    console.log(`b = ${b}`);
}


function solveThis(solveFunction){
    const readline = require('readline');
    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
    });
    
    rl.on('line', function (line) {
        input = [line][0]; 
        // 1.
        // line은 terminal에서 사람이 입력하는 명령어라고 상상해보세요.
        // "Hello World" 라는 문자열처럼, 한 줄로 표현 가능한 데이터가 들어옵니다.
        // 일반적으로 [line][0] 이라는 하드코딩은 나쁜 습관으로 받아들여집니다.
        // 물론 입력은 여러 줄로 나뉘어 들어올 수도 있습니다.
        // 그러나 프로그래머스의 문제 풀이 시스템은 항상 한 줄의 입력만 줍니다.
        // 기대하는 예외상황을 핸들링하는 코드는 좋지만
        // 벌어지지 않을 상황을 처리하는 코드는 역시 나쁩니다.
    }).on('close', solveFunction);
        // 2.
        // 문제풀이에서는 입력을 받았으면 출력을 하는게 도리입니다.    
        // 무엇을 출력할지 즉시 이곳에 기술하지 않고 callback 함수로 전달합니다.
    
    return rl;
}; 
```

2023-08-10 01:44 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +    n % 2 === 0 ? console.log(`${n} is even`) : console.log(`${n} is odd`);
`판단을 하고 출력 포맷을 만든다. 출력을한다. `
이 두 가지 작업을 동시에 한 줄에 하는 것이 좋지 않다는 이야기예요.
판단하고 출력 포맷 만들기와
출력을 구분하는게 일반적으로 읽기에 스트레스가 덜해요.

이렇게 고친 코드와 비교해보세요.

```javascript
var oupString = n % 2 === 0 ? `${n} is even` : `${n} is odd`;

console.log(oupString);
```

삼항연산자를 싫어하는 이유가 또 있어요.
현실의 요구사항은 비논리적이기 때문에 조건이 변경되는 경우가 많습니다.
삼연산자는 조건이 변경되면 코드를 통째로 수정해야 합니다.

'지금은 조건이 두 개니까 삼항연산자 써야지' 라고 생각할 수 있겠지만
서비스를 개발하다보면 그 조건이 점점 늘어납니다.

2023-08-10 01:47 UTC, mang022 commented on javascript/song/ex000_001.js
> +  if (op === ">=") {
switch case 문으로 변경해보세요. 같은 값에 대해서 여러 분기 처리를 할 때는 switch case가 훨씬 가독성이 좋습니다.

2023-08-10 01:49 UTC, mang022 commented on javascript/song/ex000_001.js
> +  if (fnum > snum || fnum === snum) {
>= 연산자와 같은 의도가 맞을까요?

2023-08-10 01:49 UTC, mang022 commented on javascript/song/ex000_001.js
> +  return fnum > snum || fnum === snum ? fnum : snum;
">=" 연산자와 같은 의도가 맞을까요?

2023-08-10 03:44 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +  });
이렇게 하면 나는 문제 풀이는 ex1, ex2.. 시리즈로 작성할 수 있고,
문제 해결은 solveThis 함수가 알아서 해줄거라고 기대할 수 있죠.

"입력 받고, 요구사항에 맞는 코드 작성하고, 출력하고"

라는 복잡한 사고를

"요구사항에 맞는 코드를 작성하고" 로 바꿀 수 있어요.

2023-08-10 06:04 UTC, mang022 commented on javascript/song/ex000_001.js
> +function ex20(a, b, flag) {
개발하실 때 참고하세요.

공통된 부분과 조건문으로 변경되는 부분을 나눠서 생각하면 코드를 이해하는데 더 도움이 됩니다.

여기서는 공통된 부분이 return a 
변경되는 부분이 b 또는 -b 죠.

let c = -b;
if (flag) {
  c = b;
}
return a+c;

이렇게 개발하면 조건문을 해석할 때 공통되는 부분인 a 대해서는 전혀 생각할 필요가 없게 됩니다.

2023-08-11 01:18 UTC, merged