Feature/day10 sky
lokks307/training-newbie pull request #35
Opened 2023-08-21 11:52 UTC by SKY0514

문제 136 ~ 156번까지 풀이

2023-08-22 08:51 UTC, mang022 commented on javascript/ShinGiyoung/Level0_11.js
> +    for (let j = 0; j < n; j++) {
초기화를 하실 때 반복문을 많이 사용하시는 것 같아요.

초기화는 처음 선언하실 때 하는 것이 가장 좋습니다. 그럼 이후에 생각을 안 해도 되기 때문이죠.

또한 이 문제는 O(n)으로 풀 수 있는 문제를 O(n^2)으로 풀고 있죠.
c * O(n)은 괜찮지만 O(n^2)은 괜찮지 않아요.

```
const arr = Array(n).fill(0);
arr[i] = 1;
answer.push(arr);
```

i index 안의 초기화할 때 기본값을 선언하면 반복문을 사용하지 않아도 돼요.
앞으로 다른 문제 푸실 때도 참고해보세요.

2023-08-22 13:59 UTC, doscode-kr commented
아직 못봤는데, 거의 다 왔네요!

2023-08-25 00:20 UTC, doscode-kr requested changes

2023-08-25 00:20 UTC, doscode-kr commented on javascript/ShinGiyoung/Level0_11.js
> +  }
잘하셨어요. split은 한 번만 해도 돼요. 이렇게요.

```js
for (const num of quiz) {
    const [x, op, y, , z] = num.split(" ");
    const result = operators[op](Number(x), Number(y));
    answer.push(result === Number(z) ? "O" : "X");
  }
```

2023-08-25 00:20 UTC, doscode-kr commented on javascript/ShinGiyoung/Level0_11.js
> +  const duplicateValue = s1.filter((it) => s2.includes(it));
👍

2023-08-25 00:20 UTC, doscode-kr commented on javascript/ShinGiyoung/Level0_11.js
> +    x = calculator[operator](x, y);
잘한다 💯

2023-08-25 00:20 UTC, doscode-kr commented on javascript/ShinGiyoung/Level0_11.js
> +    n % i === 0 && answer.push(i);
어디서 또 이상한걸 ㅋㅋㅋㅋ

그냥 이렇게 하셔도 괜찮아요.

```js
    if (n % i === 0) {
      answer.push(i);
    }
```

2023-08-25 00:20 UTC, doscode-kr commented on javascript/ShinGiyoung/Level0_11.js
> +  let stringToArr = [...s];
stringToArr보다는 strList 라는 이름이 더 치고 읽기 쉽고 기타등등..

2023-08-25 00:20 UTC, doscode-kr commented on javascript/ShinGiyoung/Level0_11.js
> +  }
지금 다시 보면 

```js
    if (alphabetCount[str] === undefined) {
      alphabetCount[str] = 0;
    }
    alphabetCount[str]++;
```

stringToArr에서 나온건 str일까 char일까

이 코드는

```js
    alphabetCount[ch] = (alphabetCount[ch] || 0) + 1;
```

한 줄로 쓸 수 있어요

2023-08-25 00:20 UTC, doscode-kr commented on javascript/ShinGiyoung/Level0_11.js
> +    alphabetCount[alp] === 1 && answer.push(alp);
이거 보고 위의 코드를 만들었어요.

2023-08-25 00:20 UTC, doscode-kr commented on javascript/ShinGiyoung/Level0_11.js
> +    alphabetCount[alp] === 1 && answer.push(alp);
다시봐도 안 인숙해.. 👀

2023-08-25 00:20 UTC, doscode-kr commented on javascript/ShinGiyoung/Level0_11.js
> +}
다음에는 이름 잘 지어주세요

2023-08-25 00:20 UTC, doscode-kr commented on javascript/ShinGiyoung/Level0_11.js
> +    str === str.toLowerCase() ? str.toUpperCase() : str.toLowerCase(),
ch !

2023-08-25 00:20 UTC, doscode-kr commented on javascript/ShinGiyoung/Level0_11.js
> +  const password = stringToArr.filter((str, idx) => {
다 str로 썼어요 ㅋㅋ 이건 습관 때문입니다.

2023-08-25 00:20 UTC, doscode-kr commented on javascript/ShinGiyoung/Level0_11.js
> +    /3|6|9/g.test(num) && count++;
정규식의 여왕. 그런데 자꾸 이상한 문법을 씀ㅋㅋ

2023-08-25 00:20 UTC, doscode-kr commented on javascript/ShinGiyoung/Level0_11.js
> +  let removeDuplication = new Set([...my_string]);
👍

2023-08-27 02:18 UTC, merged