Feature/day2
lokks307/training-newbie pull request #4
Opened 2023-08-10 08:45 UTC by redcatsh

2023-08-10 09:22 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +  ex2Output(input.split(" "));
ex3이 ex2Ouput을 호출해요.

2023-08-10 09:27 UTC, doscode-kr requested changes

2023-08-10 09:27 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +  ex3Output(input.split(" "));
ex4가 ex3 Output을 호출해요

2023-08-10 09:27 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +  ex5Output(input.split(" "));
정답을 하나씩 밀려쓰고 있어요 ㅋㅋ

2023-08-10 09:27 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +  for (let i = 0; i < input.length; i++) {
인덱스를 반드시 써야하는 이유가 있나요?

배열의 모든 원소를 순회하는 경우
forEach나 for ... of 를 사용하는게 좋아요.

2023-08-10 09:27 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +    console.log(`${n} is even`);
낮에 이 방식에 대한 코멘트가 있었던 것 같은 느낌...?

2023-08-10 10:25 UTC, redcatsh commented on javascript/song/ex000_001.js
> +  for (let i = 0; i < input.length; i++) {
문자열을 순회해서 for문을 썼는데 그럼 배열로 바꿔주고 for each나 for of를 쓰면 되나요?

2023-08-10 10:31 UTC, redcatsh commented on javascript/song/ex000_001.js
> +    console.log(`${n} is even`);
삼항연산자는 쓰지 말라고 하셔서 if문으로 바꾼건데.. 제가 잘못 이해한 걸까요..?ㅎㅎ

2023-08-10 11:06 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +  for (let i = 0; i < input.length; i++) {
아 제가 코드만 봐서! 미안해요 ^^;

2023-08-10 11:07 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +    console.log(`${n} is even`);
연산과 출력을 분리하는게 더 낫다는 말을 했었죠
연산 결과를 변수에 담고  console.log를 가장 마지막에 한 번만 하는게 더 좋아요.

2023-08-10 11:07 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +    return fnum;
위에 남긴 코멘트랑 비슷해요

2023-08-10 11:09 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +  } else return snum;
else가 필요하지 않을지도 몰라요.

2023-08-10 11:23 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +
```javascript
function solution(n) {
      let arr = [];
      for (let i = 1; i <= n; i++) {
        arr.push(i);
      }
    
      if (n % 2 === 1) {
        arr = arr.filter((el) => el % 2 === 1);
      } else {
        arr = arr.filter((el) => el % 2 === 0);
        arr = arr.map( (n) => n**2);
      }
    
    const result = arr.reduce(function add(sum, currValue) {
      return sum + currValue;
    }, 0);
    
    return result;
}

```

2023-08-10 11:24 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +
이 두 개의 코드를 주석으로 해설해보시겠어요?
색다른 느낌을 받을 거예요.

2023-08-10 11:58 UTC, redcatsh commented on javascript/song/ex000_001.js
> +
제가 작성한 코드가 바보같네요..

2023-08-10 12:09 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +  for (let i = 0; i < input.length; i++) {
이 방법과 비교해보세요
```javascript
  const arr = [...str]
  arr.map ( (ch) => console.log(ch));
```

2023-08-10 12:13 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +    answer = 1;
answer는 없어도 될 것 같아요.

```javascript
if (result)
    return 1
return 0

```

2023-08-10 12:17 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +  apow = Math.pow(a, 3);
되긴 하는데 `const` 나 let 이 있는게 더 좋을 것 같아요.

2023-08-10 12:23 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +}
```javascript
function solution(a, b, c) {
  const apow = Math.pow(a, 3);
  const bpow = Math.pow(b, 3);
  const cpow = Math.pow(c, 3);

  const sum = a + b + c;
  const sumOfSquares = a ** 2 + b ** 2 + c ** 2;
  const sumOfCubics = apow + bpow + cpow;

  if (areAllEqual(a, b, c)) {
    return sum * sumOfSquares * sumOfCubics;
  } 
  if (areAnyEqual(a, b, c)) {
    return sum * sumOfSquares;
  }

  return sum;
}

function areAllEqual(...values) {
  return values.every(v => v=== values[0]);
}

function areAnyEqual(...v) {
  return v[0] === v[1] || v[0] === v[2] || v[1] === v[2];
}
```

2023-08-10 12:24 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +}
이것도 각 코드 라인을 주석으로 해석하다보면 차이점을 느낄 수 있을 거예요.

2023-08-10 12:25 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +
이 과정 거치면 `나 좀 쩌는데` 라고 생각하실 거예요. 걱정마세요.

2023-08-10 12:41 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +  return num % n === 0 ? 1 : 0;
true를 1로, false를 0으로 치환하는 요구사항이 많네요.
그런 역할을 하는 함수를 하나 만들고, 다른 문제를 풀 때 재사용하는게 어떨까요?

2023-08-10 12:44 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +
네, 시도해보다가 어려우면 이렇게 흔적과 메모를 남기시면 돼요.
다 못풀어도 괜찮아요. 
더 좋은 문법으로 코드를 작성하는 것이 목적이예요.

```javascript

function solution(code) {
    let mode = 0;
    let ret = '';

    for (let idx = 0; idx < code.length; idx++) {
        if (code[idx] === "1") {
            mode = 1 - mode;
            continue;
        }
        if ((mode === 0 && idx % 2 === 0) || (mode === 1 && idx % 2 === 1)) {
            ret += code[idx];
        }
    }

    if (isEmpty(ret))
        return "EMPTY"

    return ret
}

function isEmpty(s){
    if (s === '')
        return true

    return false;
}
```

2023-08-10 13:37 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +
이제 else 안 쓰는거 👍

2023-08-10 15:32 UTC, redcatsh commented on javascript/song/ex000_001.js
> +
감사합니다 👍🏻

2023-08-11 01:18 UTC, doscode-kr commented
커밋이 많아 로딩이 길어지네요
지금까지 하신 건 머지할게요.
잘 하셨어요 👍

2023-08-11 01:18 UTC, merged