training/day3
lokks307/training-newbie pull request #9
Opened 2023-08-11 05:31 UTC by redcatsh

2023-08-11 15:07 UTC, doscode-kr requested changes

2023-08-11 15:07 UTC, doscode-kr commented on javascript/song/ex000_001.js
>    return answer;
27번 문제 푸는 스타일로 수정해보세요

2023-08-11 15:39 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +
arr의 모든 원소를 순회하는 문제니까 for .. of 를 사용하는게 더 낫습니다. 그러면
arr[i] 대신  
num으로 읽을 수 있죠..

```javascript
  function ex35BuildArray4(arr) {
  const stack = []; // stk

  for (const num of arr) {
    
    if (stack.length && stack[stack.length - 1] >= num) {
      stack.pop();
    }
    stack.push(num);
  }

  return stack;
}

```

ex35는 문제 낸 사람이 문제를 너무 어렵게 설명한거 같아요.
뭔 소린가 이해가 안 되어 한참 읽어봤는데, i가 필요하지 않아요.

... 이런 일은 현실에서도 많이 벌어집니다... -_-)...

복잡하지 않은걸 복잡하게 설명하는 사람들이 있거든요

2023-08-11 15:42 UTC, doscode-kr requested changes

2023-08-11 15:42 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +  return answer;
answer 없이 return 하는게 더 좋겠어요

2023-08-13 13:22 UTC, redcatsh commented on javascript/song/ex000_001.js
> +    if (i % 5 !== 0) continue;
앗,, 어차피 아래에서 원소가 5와 0으로 이루어져 있는지 검증하기 때문에 해당 조건이 필요없네요..😅

2023-08-13 13:54 UTC, redcatsh commented on javascript/song/ex000_001.js
> +
근데 알려주신 방법을 프로그래머스로 제출해보면 틀렸다고 나와요..🥲🥲

그리고 또 잘 이해가 가지 않는 부분이, 알려주신 로직대로 실행한다면

stack이 초기에는 빈 배열이니까 stack.push(num)이 실행되서 
stack=[1]이 되고,
현재 stack의 마지막 원소는 1이고 num의 두번째 원소 4보다 작으니 stack.push(num)이 되서 
stack=[1,4]이고,
현재 마지막 원소는 4이고 num의 세번째 원소 2보다 크니 stack.pop()이 되서 
stack=[1]이 되고,
현재 마지막 원소는 1이고 num의 네번째 원소 5보다 작으니 stack.push(num)이 되서
stack=[1,5]가 되고,
현재 마지막 원소가 5이고 num의 마지막 원소 3보다 크니 stack.pop(num)이 되서
결국엔 stack=[1]이 되는게 아닌가요..?

근데 테스트케이스는 통과되고,, 뭔가 제가 잘못 해석하고 있는 건가요..?ㅜㅜ

2023-08-14 07:19 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +
오 그러네. 제가 잘못 알려드린거 같습니다 ㅡ.ㅡ;;; 
제출을 안 눌러보고 테스트 케이스만 보고 했더니...!
다음에는 제출해서 다른 케이스에도 대응하는지 보고 말씀드릴게요. 혼란을 드려 미안해요 ^^;;

2023-08-14 07:24 UTC, doscode-kr commented on javascript/song/ex000_001.js
> +
if를 while로 바꾸시면 ^^; 동작할거예요.
```js
function ex35BuildArray4(arr) {
  const stack = []; 
  for (const num of arr) {
    while (stack.length && stack[stack.length - 1] >= num) {
      stack.pop(); // stk의 마지막 원소 제거
    }
    stack.push(num); // stk에 num 추가
  }
  return stack; // 최종적으로 생성된 stk 반환
}

```

2023-08-14 07:24 UTC, merged